version: "3"

services:
  ojilab:
    build:
      context: .
    container_name: ojilab
    environment:
      - VIRTUAL_HOST=ojilab.cloud
    restart: always

networks:
  default:
    external:
      name: proxy
